Compuzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import include,path
from .views import Delus, Userdet,loginredirect,Crus,editus,logoutredirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
urlpatterns=[
    path('', include('django.contrib.auth.urls'),name='authen'),
    path('register/', Crus.as_view(),name='register'),
    path('userprofile/<int:pk>', login_required(Userdet.as_view()),name='userdetails'),
    path('loginredirect/',loginredirect,name='loginredirect'),
    path('edituser/<int:pk>',login_required(editus.as_view()),name='edituser'),
    path('deleteuser/<int:pk>',login_required(Delus.as_view()),name='deleteuser'),
    # path('logoutredirect/', logoutredirect, name='logoutredirect')
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required



app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('products/<int:id>', views.products, name="products"),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('delete/<int:id>/', login_required(views.delete.as_view()), name='delete'),
    path('addproduct', login_required(views.add_product.as_view()),name='addproduct'),
    path('edit/<int:pk>', login_required(views.edit.as_view()),name='edit'),
    path('cat_list', views.cat_list, name='cat_list'),
    path('category/<str:category>/', views.cat_det, name='cat_det'),
]
# handler404 = 'views.custom_404'

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User

class catg(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class comps(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="home/images", null=True, blank=True, help_text="Enter an image URL or upload an image.")
    price = models.IntegerField()
    description = models.TextField()
    in_stock = models.BooleanField()
    category = models.ForeignKey(catg, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)

    def get_image_url(self):
        return f"/media/{self.image}"

    def __str__(self):
        return self.name




    # image = models.CharField(max_length=200, null=True, blank=True, help_text="Enter an image URL or upload an image.")
    #
    # def get_image_url(self):
    #     if self.image.startswith(('http://', 'https://')):
    #         return self.image
    #     else:
    #         return self.image.url if self.image else None
    #
    # def __str__(self):
    #     return f"{self.image} - {self.id}"

accounts/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from .form import Reg, Ed
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

class Userdet(DetailView):
    model = User
    template_name = 'accounts/prof.html'
    context_object_name = 'userdata'

class editus(UpdateView):
    model = User
    template_name = 'accounts/edus.html'
    success_url = reverse_lazy('loginredirect')
    form_class = Ed
    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request,user)
        return response
class Crus(CreateView):
    model = User
    template_name = 'accounts/reg.html'
    form_class = Reg
    success_url = reverse_lazy('loginredirect')
    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return response

class Delus(DeleteView):
    model = User
    template_name = 'accounts/delus.html'
    success_url = reverse_lazy('home:home')

@login_required()
def loginredirect(request):
    return redirect('userdetails', pk=request.user.id)
@login_required
def logoutredirect(request):
    return render(request, 'registration/logout.html')

home/views.py
from django.shortcuts import render

# Create your views here.
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.urls import reverse_lazy
from .models import comps, catg
from django.views.generic import ListView,DetailView
from django.views.generic.edit import UpdateView, DeleteView,CreateView

def home(request):
    products = comps.objects.all()
    return render(request, template_name='home/index.html', context={"products": products})

def products(request, id):
    product = get_object_or_404(comps, id=id)
    return render(request, template_name='home/products.html', context={"product": product})

def contact(request):
    return render(request, template_name='home/contact.html')

def about(request):
    return render(request, template_name='home/about.html')



def search(request):
    query = request.GET.get('query')
    comps_result = comps.objects.filter(name__icontains=query)

    context = {
        "products": comps_result,
        "query": query
    }
    return render(request, 'home/search.html', context)


# def delete(request, id):
#     comp = get_object_or_404(comps, id=id)
#
#     if comp:
#         comp.delete()
#         return redirect('/')
#     else:
#         return HttpResponse("Sorry, Computer Part Not Found !!")

class prodedform(forms.ModelForm):
    class Meta:
        model = comps
        exclude = ['owner']

class edit(UpdateView):
    model = comps
    template_name = 'home/addprod.html'
    form_class = prodedform
    success_url = reverse_lazy('home:home')
    def form_valid(self, form):
        if self.get_object().owner == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponseForbidden(render(self.request, 'home/forbid.html').content)

class delete(DeleteView):
    model = comps
    template_name = 'home/delete.html'
    success_url = reverse_lazy('home:home')
    def form_valid(self, form):
        if self.get_object().owner == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponseForbidden(render(self.request, 'home/forbid.html').content)

class add_product(CreateView):
    model = comps
    template_name = 'home/addprod.html'
    form_class = prodedform
    success_url = reverse_lazy('home:home')
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

def cat_det(request, category):
    cats = comps.objects.filter(category__name=category)
    context = {
        'comps': cats,
        'category': category
    }
    return render(request, 'home/cat_det.html', context)
def cat_list(request):
    categories = catg.objects.all()
    context = {
        'categories': categories}
    return render(request, 'home/cat.html', context)

def custom_404(request, exception):
    return render(request, 'custom_404.html', status=404)

accounts/templates/accounts/delus.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
    <form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <div style=" font-weight: bold; font-size: 20px"
     class="d-flex flex-column align-items-center justify-content-around">
    <p> Are You Sure You Want To Delete your profile ? </p>
    <button type="submit" class="btn btn-danger">Submit</button>
            <a href="/" class="btn btn-dark">Cancel</a>
                </div>
</form>

{% endblock %}

accounts/templates/accounts/edus.html
{% extends 'home/base.html'%}
{% block content%}
<form method="post" >
    {%csrf_token%}
    <div style="display: flex; flex-direction: column; width: 80%; margin-left: 10%;
     margin-bottom: 2rem; margin-top: 2rem;height:25rem;justify-content: space-around">
    {{form}}
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>
{% endblock%}

accounts/templates/accounts/prof.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
{% if user.id == userdata.id %}
<div style="height: auto;width: 20rem; margin-top: 2rem;margin-bottom: 2rem" class="container">
  <div class="card detail-card">
    <div class="card-body">
      <h5 class="card-title">First Name: {{ userdata.first_name }}</h5>
      <p class="card-text">Last Name: {{userdata.last_name }}</p>
      <p class="card-price">Email: {{ userdata.email }}</p>
      <a href="/accounts/edituser/{{userdata.id}}" class="btn btn-warning">Edit</a>
      <a href="/accounts/deleteuser/{{userdata.id}}" class="btn btn-danger">Delete</a>
    </div>
<!--    <a href="/" class="btn btn-primary home-btn">Back To Products</a>-->
  </div>
{% else %}
  <h1>You Are Not Authorized !!!!!!</h1>
  {%endif%}
</div>

{% endblock %}

accounts/templates/accounts/reg.html
{% extends 'home/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <div style="display: flex; flex-direction: column; width: 80%; margin-left: 10%; margin-bottom: 2rem; margin-top: 2rem; height: 25rem; justify-content: space-around">
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
{% endblock %}

home/templates/home/about.html
{% extends 'home/base.html' %}
{% block content %}

<div class="container">
    <div class="row row-cols-2 m-5">
        <div class="col-6 d-flex justify-content-center align-items-center" style="border-right: 1px solid black;">
            <h1>Know more about Compuzone!</h1>
        </div>
        <div class="col-6 ps-5">
            <h2>Vision</h2>
            <p class="ps-5">We try to offer the best computer Parts in the Market!</p>
            <hr>
            <h2>Mission</h2>
            <p class="ps-5">Create the best offers & deals for customer needs!</p>

        </div>
</div>
</div>

{% endblock %}

home/templates/home/addprod.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<style>
    .errorlist li{
        color: red;
    }
</style>

    <form method="post"  enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <div style=" font-weight: bold; font-size: 20px"
     class="d-flex flex-column align-items-center justify-content-around">
        {{form}}
    <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

{% endblock %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compuzone</title>
    <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'home/bootstrap/js/bootstrap.js' %}"></script>
    
</head>
<body class="d-flex flex-column min-vh-100">

    {% include 'home/header.html' %}

    <main>{% block content %} {% endblock %}</main>

    {% include 'home/footer.html'%}

</body>
</html>

home/templates/home/cat.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="card-container">

    {% for cat in categories %}
    <div class="card">
        <h2>{{ cat.name }}</h2>
        <h5>Category: {{ product.category }}</h5>
        <p>{{cat.description}}</p>

        <a href="{% url 'home:cat_det' category=cat.name %}" class="btn">Products Category</a>
        {% comment %}
        <a href="{% url 'edit_gun' id=gun.id %}" class="btn bg-warning">Edit</a>
        <a href="{% url 'delete' id=gun.id %}" class="btn bg-danger">Delete</a> {% endcomment %}
    </div>
    {% endfor %}
</div>
{% endblock %}

home/templates/home/cat_det.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row g-5">
         <h2> Category: {{ category }}</h2>
        {% for prod in comps %}
        <div class="col-12 col-md-6 sec-border p-3">
            <img class="w-100 product-main-img" src={{prod.image.url}} alt=""></img>
        </div>

        <div class="col-12 col-md-6">
            <div class="mb-5">
                <h1>{{prod.name}}</h1>
                <p class="text-wrap">{{prod.description}}</p>
                <h2>$ {{prod.price}}</h2>
                <p>Category: {{ prod.category }}</p>
            </div>
            <hr/>
            <div class="mb-5">
                <div class="d-flex justify-content-around align-items-center mb-5">
                    <p>{{prod.stock}} Items In Stock</p>
                </div>
            </div>
            <a href="/"><button class="btn btn-primary">Back to home</button></a>
            <a href="/delete/{{prod.id}}"><button class="btn btn-danger">Delete</button></a>
            <a href="/edit/{{prod.id}}"><button class="btn btn-warning">Edit Product</button></a>
        </div>
          {% endfor %}
    </div>
</div>
{% endblock %}

home/templates/home/contact.html
{% extends 'home/base.html' %}
{% block content %}

<div class="container">
    <div class="row m-5">
        <div class="col-6 d-flex justify-content-center align-items-center">
            <h1>Get in touch!</h1>
        </div>
        <div class="col-6">
            <h2>Email us:</h2>
            <p class="ps-5">compuzone@amazon.org</p>
            <br>
            <h2>Phone</h2>
            <p class="ps-5">+201025811792</p>
            <br>
            <h2>Address</h2>
            <p class="ps-5">Redmond, Wa, Usa</p>
        </div>
</div>
</div>

{% endblock %}

home/templates/home/footer.html
<footer class="bg-light text-center text-lg-start mt-auto">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 3);">

      <a class="text-light" href="/">© 2023 Copyright: Compuzone.com</a>
    </div>
  </footer>

home/templates/home/forbid.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<style>
    body {
        background-image: url('/media/home/images/13.png');
        background-size: cover;

    }
</style>

{% endblock %}

home/templates/home/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: rgba(0, 0, 0, 3);">
    <div><a href="/"><strong>Compuzone</strong></a></div>
    <div class="container-fluid justify-content-center">
      <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about/">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/contact/">Contact us</a>
          </li>

        </ul>
      </div>
    </div>

    <div class="navbar-right ml-auto d-flex justify-content-right">
                <form action="{% url 'home:search' %}" method="GET">
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" name="query" class="form-control form-control-md" placeholder="Search...">
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                    </div>
                </form>
    </div>
     <div class="navbar-right ml-auto d-flex justify-content-right col-md-2">
         <ul class="navbar-nav">
         <li class="nav-item">
             <a class="nav-link btn btn-danger btn-sm " href="{% url 'home:addproduct' %}">Add Product</a>
         </li>
         <li class="nav-item">
              <a class="nav-link btn btn-light btn-sm" href="{% url 'home:cat_list' %}">Show Categories</a>
         </li>
         </ul>
     </div>
    <div style="margin-right: 1rem; width: 18rem" class="d-flex justify-content-around">
          {% if user.id %}
           <a href="accounts/userprofile/{{user.id}}"><p style="font-weight: bold; font-color: white; font-size: 15px; margin: 0" >Welcome, {{user}}</p></a>
           <a style="font-weight: bold; font-size: 20px;margin: 0" class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a style="font-weight: bold; font-size: 20px;margin: 0" class="btn btn-warning" href="accounts/login/">Login</a>
          <a style="font-weight: bold; font-size: 20px;margin: 0" class="btn btn-warning" href="{% url 'register' %}">Register</a>
          {% endif %}
      </div>
</nav>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}

<div class="container">
    <div class="row g-3">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-2 border-0 vh-50">
                <a href="/products/{{product.id}}"><img  src="{{product.image}}"
                class="card-img-top img-fluid rounded" alt="product thumbnail" style="height: 35vh; object-fit: cover;"/></a>
                <div class="card-body p-0 position-relative rounded mt-1">
                    <h5 class="d-inline-block card-title mt-3 w-75">{{product.name}}</h5>
                    <p class='text-secondary p-0 float-end'>Price : ${{product.price}}</p>
                    <p class='text-secondary p-0'>Category: {{ product.category }}</p>
                    <p class='text-secondary p-0'>{{product.stock}} in stock</p>
                    <p class='text-secondary p-0'>{{product.description}}</p>
                    <p class='text-secondary p-0'>Owner: {{product.owner}}</p>
                </div>
                </div>
            </div>
        {% endfor %}
        
     </div>
</div>

{% endblock %}

home/templates/home/products.html
{% extends 'home/base.html' %}
{% block content %}

<div class="container">
    <div class="row g-5">
        <div class="col-12 col-md-6 sec-border p-3">
            <img class="w-100 product-main-img" src={{product.image.url}} alt=""></img>
        </div>
        <div class="col-12 col-md-6">
            <div class="mb-5">
                <h1>{{product.name}}</h1>
                <p class="text-wrap">{{product.description}}</p>
                <h2>$ {{product.price}}</h2>
                <p>Category: {{ product.category }}</p>
                <p>Owner: {{ product.owner }}</p>
            </div>
            <hr/>
            <div class="mb-5">
                <div class="d-flex justify-content-around align-items-center mb-5">
                    <p>{{product.stock}} Items In Stock</p>
                </div>
            </div>
            <a href="/"><button class="btn btn-primary">Back to home</button></a>
            <a href="{% url 'home:delete' id=product.id %}"><button class="btn btn-danger">Delete</button></a>
            <a href="/edit/{{product.id}}"><button class="btn btn-warning">Edit Product</button></a>
        </div>
    </div>
</div>


{% endblock %}

home/templates/home/search.html
{% extends 'home/base.html' %}
{% block content %}

<div class="container">
     <h1>Search Results for<strong>"{{ query }}"</strong> </h1>
    {% if products %}
    <div class="row g-3">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-2 border-0 vh-50">
                <a href="/products/{{ product.id }}">
                    <img src="{{ product.image }}"
                         class="card-img-top img-fluid rounded"
                         alt="product thumbnail"
                         style="height: 35vh; object-fit: cover;"
                    />
                </a>
                <div class="card-body p-0 position-relative rounded mt-1">
                    <h5 class="d-inline-block card-title mt-3 w-75">{{ product.name }}</h5>
                    <p class='text-secondary p-0 float-end'>Price : ${{ product.price }}</p>
                    <p class='text-secondary p-0'>{{ product.stock }} in stock</p>
                    <p class='text-secondary p-0'>{{ product.description }}</p>
                </div>
                <a href="{% url 'home:delete' id=product.id %}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No results found.</p>
    {% endif %}
</div>

{% endblock %}